### ISSUE TITLE
Defining task level variable in input JSON file

### ISSUE THREAD

**Issue by leepc12** [dnanexus/dxWDL#128]
I cannot define task level variables directly in an input JSON file with dxWDL-0.64.

Here is an example code.
```
$ cat test_task_level_var.json
{
        "test.a" : "a",
        "test.t1.b" : "b"
}
$ cat test_task_level_var.wdl
workflow test {
        String a
        call t1 {
        }
}

task t1 {
        String b
        command {
                echo ${b}
        }
        output {
                String out = read_string(stdout())
        }
}
```

dxWDL 0.60.2 worked.
```
$ java -jar ~/dxWDL-0.60.2.jar compile test_task_level_var.wdl -f -folder /test1 -defaults test_task_level_var.json
Picked up _JAVA_OPTIONS: -Xms256M -Xmx1024M -XX:ParallelGCThreads=1
Workflow doesn't supply required input b to call t1
workflow-FG30K9Q0FkPvBvvb24y3Pz4b
```
`t1.b` is correctly set as `b`.
![image](https://user-images.githubusercontent.com/8625660/40458109-024c049c-5eaf-11e8-8ea1-2231902e4130.png)

But dxWDL 0.64 doesn't work
```
$ java -jar ~/dxWDL-0.64.jar compile test_task_level_var.wdl -f -folder /test1 -defaults test_task_level_var.json
Picked up _JAVA_OPTIONS: -Xms256M -Xmx1024M -XX:ParallelGCThreads=1
Empty output section, no outputs will be generated
Call is missing a compulsory argument.
Workflow doesn't supply required input b to call t1

test_task_level_var.wdl, line 3
        call t1 {
      ^

java.lang.Exception: Namespace failed validation
        at dxWDL.compiler.Validate$.validateNamespace(Validate.scala:250)
        at dxWDL.compiler.Validate$.apply(Validate.scala:260)
        at dxWDL.compiler.CompilerTop$.compileNamespaceOpsTree(CompilerTop.scala:122)
        at dxWDL.compiler.CompilerTop$.apply(CompilerTop.scala:220)
        at dxWDL.Main$.compile(Main.scala:395)
        at dxWDL.Main$.dispatchCommand(Main.scala:572)
        at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:619)
        at dxWDL.Main$delayedInit$body.apply(Main.scala:13)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at dxWDL.Main$.main(Main.scala:13)
        at dxWDL.Main.main(Main.scala)
```

**Comment by orodeh** [comment]
@leepc12, I think release 0.66 (https://github.com/dnanexus/dxWDL/releases/tag/0.66) has a solution for this. It supports setting default values for tasks through the `--defaults` flag. Please check it out.

**Comment by leepc12** [comment]
I tested the above code with dxWDL-0.66 but got the same error.

If I make the task-level variable optional (with `?`), then I get the following error:
```
$ java -jar ~/dxWDL-0.66.jar compile test_task_level_var.wdl -f -folder /test_task_level_var -defaults test_task_level_var.json
Picked up _JAVA_OPTIONS: -Xms256M -Xmx1024M -XX:ParallelGCThreads=1
Empty output section, no outputs will be generated
Could not map all default fields.
These were left: Map(test.t1.b -> "b")
java.lang.Exception: Failed to map all default fields
        at dxWDL.compiler.InputFile.embedDefaults(InputFile.scala:216)
        at dxWDL.compiler.Top$.compileIR(Top.scala:131)
        at dxWDL.compiler.Top$.apply(Top.scala:207)
        at dxWDL.Main$.compile(Main.scala:398)
        at dxWDL.Main$.dispatchCommand(Main.scala:584)
        at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:636)
        at dxWDL.Main$delayedInit$body.apply(Main.scala:12)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at dxWDL.Main$.main(Main.scala:12)
        at dxWDL.Main.main(Main.scala)
```

**Comment by orodeh** [comment]
Can you try: 
```
{
  "t1.b" : "b" 
} 
```

Setting the key `test.t1.b` is not currently supported. It would require going through the workflow and finding all the cases where `t1` is called. The implementation in 0.66 builds value `b` into task `t1`, not into the workflow.

**Comment by leepc12** [comment]
Yes, it worked.

But it would be better if we can use the same input JSON file for both cromwell and dxWDL cause  `[WORKFLOW].[TASK].[VAR]` is a WDL standard.

Is it possible for your JSON parser to automatically remove `[WORKFLOW].` from `[WORKFLOW].[TASK].[VAR]` until `test.t1.b` is truly supported in later versions?

**Comment by orodeh** [comment]
@leepc12, these things are similar, but not the same.
 
1) `[WORKFLOW].[TASK].[VAR]` sets argument `VAR` for one particular call to `task`. 
2) `[TASK].[VAR]` sets `VAR` for all cases where `TASK` is called.

Currently, only case (2) is supported. We can think about implementing case (1).

**Comment by orodeh** [comment]
I am closing this issue, because case 1 is actually quite different. I don't know if we will ever fully support it.
