### ISSUE TITLE
ignoring unsupported runtime attributes

### ISSUE THREAD

**Issue by leepc12** [dnanexus/dxWDL#133]
Here is my pipeline's workflow option for cromwell. Cromwell automatically ignores runtime attributes that are not supported by a specific backend. So I can use one file for multiple backends (google cloud, slurm, sge, local, ...). I would like to use the same file for dxWDL too.
```
$ cat workflow_opts/docker.json
{
    "default_runtime_attributes" : {
        "docker" : "quay.io/encode-dcc/atac-seq-pipeline:v1",
        "zones": "us-west1-a us-west1-b us-west1-c us-central1-c us-central1-b",
        "failOnStderr" : false,
        "continueOnReturnCode" : 0,
        "preemptible": "0",
        "bootDiskSizeGb": "10",
        "noAddress": "false"
    }
}
```

dxWDL is too strict for this. It would be better if dxWDL can just ignore (with a warning) unsupported runtime attributes.
```
$ java -jar ~/dxWDL-0.66.jar compile atac.wdl -f -folder /dxWDL-66 -defaults examples/dx/ENCSR356KRQ_subsampled_chr19_only_dx.json -extras workflow_opts/docker.json
Picked up _JAVA_OPTIONS: -Xms256M -Xmx1024M -XX:ParallelGCThreads=1
java.lang.Exception: Unsupported runtime attribute preemptible,we currently support Set(dx_instance_type, disks, docker, cpu, memory)
        at dxWDL.Extras$.$anonfun$parseRuntimeAttrs$1(Extras.scala:277)
        at dxWDL.Extras$.$anonfun$parseRuntimeAttrs$1$adapted(Extras.scala:273)
        at scala.collection.Iterator.foreach(Iterator.scala:944)
        at scala.collection.Iterator.foreach$(Iterator.scala:944)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
        at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:178)
        at dxWDL.Extras$.parseRuntimeAttrs(Extras.scala:273)
        at dxWDL.Extras$.parse(Extras.scala:405)
        at dxWDL.Main$.compilerOptions(Main.scala:322)
        at dxWDL.Main$.compile(Main.scala:390)
        at dxWDL.Main$.dispatchCommand(Main.scala:584)
        at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:636)
        at dxWDL.Main$delayedInit$body.apply(Main.scala:12)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at dxWDL.Main$.main(Main.scala:12)
        at dxWDL.Main.main(Main.scala)
```

**Comment by orodeh** [comment]
@leepc12, release [0.66.1](https://github.com/dnanexus/dxWDL/releases/tag/0.66.1) fixes this problem.

**Comment by leepc12** [comment]
Thanks, it works!
