### ISSUE TITLE
When a call, input, and output all have the same name...

### ISSUE THREAD

**Issue by mlin** [dnanexus/dxWDL#140]
To my mind, `cram = cram.cram` in the following example, while dumb, is valid:

```
workflow x {
    call cram
    call y { input:
        cram = cram.cram
    }
}

task cram {
    command {
        echo "."
    }
    output {
        String cram = "."
    }
}

task y {
    String cram
    command {
        echo "."
    }
}
```

But it fails compiling:

```
$ java -jar dxWDL-0.66.2.jar compile x.wdl 
Error loading WDL source code
wdl.draft2.parser.WdlParser$SyntaxError: ERROR: Bad target for member access 'cram.cram': 'cram' was a String (line 4, col 21):

        cram = cram.cram
                    ^
     
	at wdl.draft2.model.WdlNamespace$.checkValidityOfMemberAccess$1(WdlNamespace.scala:493)
	at wdl.draft2.model.WdlNamespace$.$anonfun$validateCallInputSection$8(WdlNamespace.scala:516)
	...
```

Is this an upstream issue?

**Comment by orodeh** [comment]
@mlin, this is a Cromwell problem. If you place your WDL code in file `cram.wdl`, then
```
java -jar /devel/cromwell-32.jar run cram.wdl
```
fails like this:
```
[2018-06-21 22:58:25,01] [error] WorkflowManagerActor Workflow 21e934cb-a32e-4659-9a2f-e5b271a59fa6 failed (during MaterializingWorkflowDescriptorState): Workflow input processing failed:
ERROR: Bad target for member access 'cram.cram': 'cram' was a String (line 4, col 33):

                    cram = cram.cram
                                ^
     
cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
ERROR: Bad target for member access 'cram.cram': 'cram' was a String (line 4, col 33):

                    cram = cram.cram
```
