### ISSUE TITLE
Specifying Task parameters in the cromwell input JSON, but not in the WDL task calls does not compile

### ISSUE THREAD

**Issue by Damien-Black** [dnanexus/dxWDL#175]
### Motivation

Attempting to compile and reproduce [gatk4-data-processing](https://github.com/gatk-workflows/gatk4-data-processing) WDL workflows.

### Issue

When compiling with the command

```
java -jar dxWDL-0.78.jar compile processing-for-variant-discovery-gatk4.wdl -project project-FP71ZyQ0Vvfq9g0j0G40KGYG -defaults input_files_options.json
```

The following error is encountered

```
java.lang.Exception: Could not map all default fields.
These were left: Map(PreProcessingForVariantDiscovery_GATK4.BwaMem.mem_size -> "'14 GB'", PreProcessingForVariantDiscovery_GATK4.ApplyBQSR.mem_size -> "3500 MB", PreProcessingForVariantDiscovery_GATK4.SortAndFixTags.java_opt_sort -> "-Xms4000m", PreProcessingForVariantDiscovery_GATK4.BaseRecalibrator.mem_size -> "6 GB", PreProcessingForVariantDiscovery_GATK4.SortAndFixTags.java_opt_fix -> "-Xms500m", PreProcessingForVariantDiscovery_GATK4.GatherBqsrReports.java_opt -> "-Xms3000m", PreProcessingForVariantDiscovery_GATK4.BwaMem.java_opt -> "-Xms3000m", PreProcessingForVariantDiscovery_GATK4.BaseRecalibrator.java_opt -> "-Xms4000m", PreProcessingForVariantDiscovery_GATK4.ApplyBQSR.java_opt -> "-Xms3000m", PreProcessingForVariantDiscovery_GATK4.SortAndFixTags.mem_size -> "5000 MB", PreProcessingForVariantDiscovery_GATK4.GatherBqsrReports.mem_size -> "3500 MB", PreProcessingForVariantDiscovery_GATK4.MarkDuplicates.java_opt -> "-Xms4000m", PreProcessingForVariantDiscovery_GATK4.BwaMem.num_cpu -> "16", PreProcessingForVariantDiscovery_GATK4.MarkDuplicates.mem_size -> "7 GB")
	at dxWDL.compiler.InputFile.embedDefaults(InputFile.scala:215)
	at dxWDL.compiler.Top$.compileIR(Top.scala:165)
	at dxWDL.compiler.Top$.apply(Top.scala:287)
	at dxWDL.Main$.compile(Main.scala:389)
	at dxWDL.Main$.dispatchCommand(Main.scala:609)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:672)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at dxWDL.Main$.main(Main.scala:13)
	at dxWDL.Main.main(Main.scala)
```

### Workaround

It's possible to remove the problematic parameters from the `input_files_options.json` and compile the WDL file into workflow.

**Comment by orodeh** [comment]
This was just saying that the option was not actually available in the original WDL file; the `PreProcessingForVariantDiscovery_GATK4.BwaMem.mem_size` parameter was not something you could set.
