### ISSUE TITLE
default_runtime_attributes prevent native apps from compiling in WDL workflow

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#180]
If you specify `default_runtime_attributes` in `extras.json`, then you cannot compile a native applet reference.  See error below.  Would be better if it just ignored `default_runtime_attributes` for native apps.

```
java.lang.Exception: This is a native task, a wrapper for a dnanexus call. It should
have an empty runtime section.

/build/rendered_wdl/dts.wdl, line 117
task bcl2fastq220 {
     ^

	at dxWDL.compiler.GenerateIR.dxWDL$compiler$GenerateIR$$compileTask(GenerateIR.scala:282)
	at dxWDL.compiler.GenerateIR$.$anonfun$applyRec$2(GenerateIR.scala:965)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at dxWDL.compiler.GenerateIR$.compileTasks$1(GenerateIR.scala:964)
	at dxWDL.compiler.GenerateIR$.applyRec(GenerateIR.scala:969)
	at dxWDL.compiler.GenerateIR$.apply(GenerateIR.scala:1019)
	at dxWDL.compiler.Top$.compileIR(Top.scala:162)
	at dxWDL.compiler.Top$.apply(Top.scala:287)
	at dxWDL.Main$.compile(Main.scala:389)
	at dxWDL.Main$.dispatchCommand(Main.scala:609)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:672)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at dxWDL.Main$.main(Main.scala:13)
	at dxWDL.Main.main(Main.scala)
```

**Comment by orodeh** [comment]
That is correct, because the "native applet" is just a convenient wrapper allowing you to call a regular DNAnexus applet from WDL. 

We had a situation where users specified the instance type in the runtime attributes (e.g. mem1_ssd2_x8), and it was ignored. We want to inform the user right away *not* to use these attributes.

**Comment by jtratner** [comment]
@orodeh - but this is in extras.json. So if I have one native applet I'm no longer allowed to use that in extras.json?

The behavior for that is to be overwritten by explicit specification in the task, which to me suggests it should just ignore it for native applets.

**Comment by orodeh** [comment]
Right. It will be ignored, but the user thinks that it is *not* ignored, and reports a bug. 

At least, this was the previous situation I ran into.

**Comment by orodeh** [comment]
Converted to a warning on master branch.

**Comment by jtratner** [comment]
Thanks!
