### ISSUE TITLE
dnanexus/dxwdl appears broken

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#187]
Right now, it seems like dxWDL docker image has a project hard-coded:

```
›› docker run -e DX_SECURITY_CONTEXT -e DX_PROJECT_CONTEXT_ID -v $PWD:$PWD -w $PWD dnanexus/dxwdl compile bam_chrom_counter.wdl -project jtratner
Empty output section, no outputs will be generated
java.lang.Exception: Project dxWDL_playground not found
	at dxWDL.DxPath$.lookupProject(DxPath.scala:53)
	at dxWDL.compiler.Top$.getAssetId(Top.scala:213)
	at dxWDL.compiler.Top$.compileNative(Top.scala:252)
	at dxWDL.compiler.Top$.apply(Top.scala:293)
	at dxWDL.Main$.compile(Main.scala:393)
	at dxWDL.Main$.dispatchCommand(Main.scala:614)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:678)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at dxWDL.Main$.main(Main.scala:13)
	at dxWDL.Main.main(Main.scala)
```

vs. this works

```
cd ~/dxwdl/contrib/docker; docker build --build-arg DXWDL_VERSION=0.79 -t my-dxwdl .
cd myfolder; 
›› docker run -e DX_SECURITY_CONTEXT -e DX_PROJECT_CONTEXT_ID -v $PWD:$PWD -w $PWD dxwdl compile bam_chrom_counter.wdl -project jtratner
Empty output section, no outputs will be generated
workflow-FVBK7q00vZJBg0BF6vZ4JZx7
```

How was `dnanexus/dxwdl` generated?

**Comment by jtratner** [comment]
If you don't want to rely on github releases, then one thing that could work would be to use a multi-stage build instead.

```
FROM  ubuntu:16.04 as builder
ADD . /repo
WORKDIR /repo
RUN sbt build

FROM ubuntu:16.04
RUN apt-get install open-jdk-8
COPY --from=builder /repo/dxWDL.jar dxWDL.jar
...
```

**Comment by orodeh** [comment]
dxWDL_playground is a testing project. Looks like it somehow leaked into the image. I will have to fix that.

**Comment by jtratner** [comment]
I assume it's in the jar file? (given that github release is fine)

**Comment by ying-w** [comment]
Running with `-verbose` the line before `java.lang.Exception: Project dxWDL_playground not found` is 
`Wrote intermediate representation to /tmp/dxWDL_Compile/align.ir.yaml` where `align.wdl` the file i'm compiling

**Comment by orodeh** [comment]
The problem is the configuration file embedded in the jar. It is a testing configuration, instead of a production configuration. The jar is looking for the dxwdl runtime asset in the dWDL_playground project, which is the wrong location. 

I need to build a new release to fix this.

**Comment by jtratner** [comment]
okay! to point out tho: the github release version of dxWDL-0.79.jar works fine.

It's a different jar file inside the container vs. on github:

Github:
```
root@32449369fc95:/# md5sum /dxWDL.jar
cb235849e67f74e494899f9ecfa72868  /dxWDL.jar
```

dnanexus/dxwdl:0.79
```
root@c09b55c96cc7:/# md5sum /dxWDL.jar
0f54ea40ad8dee54620b56ff710c0c5d  /dxWDL.jar
root@c09b55c96cc7:/#
```
