### ISSUE TITLE
Optional argument in sub-sub-workflow causes compilation error

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#227]
This sub-sub-workflow call at the end of this doc below (which has a default on nprocs but doesn't pass it) is valid WDL (checked with `miniwdl cromwell outer.wdl`); however it fails with:

```
+ java -jar dxWDL-1.01.jar compile outer.wdl -archive -verbose -destination jtratner:/deleteme -projectWideReuse
project ID: project-123
folder: /deleteme
IR pass
  tasks=Set(call_cnvs_lane)
  sortByDependencies List(outer, level1, call_cnvs_lane, call_level2)
    depOrder =Vector(call_cnvs_lane, call_level2, level1, outer)
  Compiling task call_cnvs_lane
  compiling workflow call_level2
  Assembling workflow backbone call_level2
    Compiling call call_cnvs_lane as stage
  compiling workflow level1
  Assembling workflow backbone level1
    Compiling call call_level2 as stage
    env =
  run_name -> SArgWorkflowInput(CVar(run_name,WomStringType,None))
  call_level2.nprocs -> SArgWorkflowInput(CVar(call_level2.nprocs,WomIntegerType,Some(WomInteger(48))))
java.lang.Exception: input <nprocs, WomIntegerType> to call <level1.call_level2> is unspecified. This is illegal in a locked workflow.
	at dxWDL.compiler.GenerateIRWorkflow.$anonfun$compileCall$1(GenerateIRWorkflow.scala:137)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at dxWDL.compiler.GenerateIRWorkflow.compileCall(GenerateIRWorkflow.scala:124)
	at dxWDL.compiler.GenerateIRWorkflow.$anonfun$assembleBackbone$2(GenerateIRWorkflow.scal...
<really huge traceback>
```

##### ==> command.sh <==
```
eval "$(dx env --bash)"
set -x
java -jar ~/Downloads/dxWDL-1.01.jar compile \
    $PWD/outer.wdl  \
    -archive -verbose \
    -destination jtratner:/deleteme \
    -projectWideReuse
```

##### ==> outer.wdl <==
```
version 1.0

import "level1.wdl"
workflow outer {
    input {
    }
    call level1.level1 {
        input:
            run_name="a",
    }
    output {
      File special_case_plots = level1.hmm_cnv_qual_metrics_json
    }
}
```

##### ==> level1.wdl <==
```
version 1.0

import "level2.wdl"

workflow level1 {
    input {
        String run_name
    }

    call level2.call_level2 {
        input:
            run_name=run_name,
    }
    output {
        File hmm_cnv_qual_metrics_json = call_level2.cnv_qual_metrics_json
    }
}
```

##### ==> level2.wdl <==
```
version 1.0

workflow call_level2 {
    input {
        String run_name
        Int nprocs = 48
    }

    call call_cnvs_lane  {
        input:
            nothing=run_name,
    }

    output {
        File cnv_qual_metrics_json = call_cnvs_lane.cnv_qual_metrics_json
    }
}

task call_cnvs_lane {
    input {
        String nothing
    }
    command <<<
        touch call_hmm_cnvs.metrics.lane.tar.gz
    >>>
    output {
      File cnv_qual_metrics_json = "call_hmm_cnvs.metrics.lane.tar.gz"
    }
}
```

**Comment by jtratner** [comment]
Seems like *any* unspecified details in any applet causes a similar exception as well :(

```
# level2.wdl
version 1.0

workflow call_level2 {
    input {
        String run_name
    }

    call call_cnvs_lane  {
        input:
            nothing=run_name,
    }

    output {
        File cnv_qual_metrics_json = call_cnvs_lane.cnv_qual_metrics_json
    }
}

task call_cnvs_lane {
    input {
        String nothing
        Int nprocs = 48
    }
    command <<<
        touch call_hmm_cnvs.metrics.lane.tar.gz
    >>>
    output {
      File cnv_qual_metrics_json = "call_hmm_cnvs.metrics.lane.tar.gz"
    }
}
```

produces

```
java.lang.Exception: input <nprocs, WomIntegerType> to call <call_level2.call_cnvs_lane> is unspecified. This is illegal in a locked workflow.
	at dxWDL.compiler.GenerateIRWorkflow.$anonfun$compileCall$1(GenerateIRWorkflow.scala:137)
```

**Comment by orodeh** [comment]
The issue is that `nprocs` has a default, but is non-optional. I modified the compiler to allow you to not specify such arguments.
