### ISSUE TITLE
Invalid workflow fragment generation (includes `.` in input name)

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#228]
This set of files (can download [here as a Gist!](https://gist.github.com/jtratner/ad67f5e484c4a80ecb7527d3ae469a8d)) causes an invalid workflow fragment to be generated with `.` in name, generating a long error message with this in the middle ([full error message is in the gist](https://gist.github.com/jtratner/ad67f5e484c4a80ecb7527d3ae469a8d#file-failure-message))
```
java.lang.Exception: WOM validation errors:
 NonEmptyList(ERROR: Unexpected symbol (line 28, col 24) when parsing '_gen10'.

Expected rbrace, got ".".

    Boolean second_task.unpassed_arg_default
                       ^

$type_e = :type <=> :lsquare $_gen21 :rsquare -> Type( name=$0, subtype=$2 )
     )

	at dxWDL.util.ParseWomSourceFile$.validateWdlWorkflow(ParseWomSourceFile.scala:388)
	at dxWDL.compiler.WdlCodeGen.standAloneWorkflow(WdlCodeGen.scala:264)
	at dxWDL.compiler.GenerateIR.compileWorkflow(GenerateIR.scala:111)
```

##### ==> command.sh <==

```
eval "$(dx env --bash)"
set -x
java -jar ~/Downloads/dxWDL-1.01.jar compile \
    $PWD/main.wdl  \
    -archive -verbose \
    -destination jtratner:/deleteme \
    -projectWideReuse

```

##### ==> main.wdl <==

```
version 1.0

import "imported.wdl"

# here's an overview of what we're doing
workflow outer {
    input {
        Array[File] arr
    }

    call imported.inner_wf {
        input:
            initial_arr=arr,
    }
}
```

##### ==> imported.wdl <==
```
version 1.0

workflow inner_wf {
    input {
        Array[File] initial_arr = []
    }

    Array[File] non_input_decl = initial_arr

    call initial_task {
        input:
    }
        call second_task {
            input:
                input_metrics=initial_task.metrics,
                non_input_decl=non_input_decl,
        }
    output {
    }
}

task initial_task {
    input {
    }
    command <<<
    >>>
    output {
        Array[File] metrics = []
    }
}

task second_task {
    input {
        Array[File] non_input_decl
        Array[File] input_metrics
        Boolean unpassed_arg_default = true
    }
    command <<<
    >>>
    output {
    }
}
```

**Comment by orodeh** [comment]
What is happening here, is that `unpassed_arg_default` becomes an input for workflow `inner_wf`, because it is unspecified. So, workflow `inner_wf` actually has the inputs:
```
input { 
   Array[File] initial_arr = []
   Boolean second_task.unpassed_arg_default
}
```

The trouble is that dxWDL doesn't currently handle `second_task.unpassed_arg_default` properly, because it has a dot inside it. There is a documentation page devoted to what the previous compiler did (https://github.com/dnanexus/dxWDL/blob/master/doc/MissingCallArguments.md). 

I am working on it.

**Comment by orodeh** [comment]
Fixed on master.
