### ISSUE TITLE
Can not parse memory specification 16GB

### ISSUE THREAD

**Issue by TMiguelT** [dnanexus/dxWDL#29]
I'm getting an error when trying to compile a workflow with the following runtime block: 
```scala
  runtime {
    docker: "biocontainers/bwa"
    memory: "16GB"
  }
```
The error is as follows:
```
java.lang.Exception: Can not parse memory specification 16GB
        at dxWDL.InstanceTypeDB.apply(InstanceTypeDB.scala:152)
        at dxWDL.CompilerFrontEnd$.calcInstanceType(CompilerFrontEnd.scala:170)
        at dxWDL.CompilerFrontEnd$.compileTask(CompilerFrontEnd.scala:483)
        at dxWDL.CompilerFrontEnd$.$anonfun$apply$2(CompilerFrontEnd.scala:876)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at dxWDL.CompilerFrontEnd$.apply(CompilerFrontEnd.scala:875)
        at dxWDL.Main$.compileBody(Main.scala:183)
        at dxWDL.Main$.compile(Main.scala:205)
        at dxWDL.Main$.dispatchCommand(Main.scala:273)
        at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:327)
        at dxWDL.Main$delayedInit$body.apply(Main.scala:14)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:378)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at dxWDL.Main$.main(Main.scala:14)
        at dxWDL.Main.main(Main.scala)
```
It seems that perhaps the [dxWDL memory specification parser](https://github.com/dnanexus-rnd/dxWDL/blob/17e3d19e820db671a11254bb7a6ca1e0cc88f5ed/src/main/scala/dxWDL/InstanceTypeDB.scala#L171) requires sizes with a space separating the amount and the unit (e.g. `16 GB`). However the (very vague) WDL spec seems to suggest that spaces aren't needed, or perhaps aren't allowed: https://github.com/broadinstitute/wdl/blob/develop/SPEC.md#memory

**Comment by orodeh** [comment]
Good catch. I have added this to my todo list.

**Comment by orodeh** [comment]
@TMiguelT, I believe release 0.33 solves this problem.

**Comment by odoublewen** [comment]
I am getting the same error today using dxWDL-1.02  --  the compile only works when I put a space between the number and the unit.  Could this be a regression?

**Comment by orodeh** [comment]
That is unexpected. 

I reproduced it locally, so now I can fix it. I'll make sure to add a regression test for this particular case.

**Comment by orodeh** [comment]
Fixed in master.
