### ISSUE TITLE
Missing optional file output causes task to error

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#290]
Running this example under dxWDL 1.16:

```
version 1.0
task really_small_example {
    command <<<
        touch something.txt
    >>>
    output {
        File? non_existent_file = "nofile"
    }
}
```

like this:

```
docker run -e DX_SECURITY_CONTEXT=$(cat ~/.dnanexus_config/environment.json| jq -r .DX_SECURITY_CONTEXT) \
    -v $PWD:/build -w /build dnanexus/dxwdl:1.16 compile example.wdl
```

Generates a task that errors like this:

```
dxWDL.base.AppInternalException: java.lang.RuntimeException: Output file nofile is missing
        at dxWDL.dx.DxUtils$.uploadFile(DxUtils.scala:364)
        at dxWDL.exec.JobInputOutput.$anonfun$delocalizeFiles$5(JobInputOutput.scala:384)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at dxWDL.exec.JobInputOutput.delocalizeFiles(JobInputOutput.scala:383)
        at dxWDL.exec.TaskRunner.epilog(TaskRunner.scala:474)
        at dxWDL.Main$.taskAction(Main.scala:546)
        at dxWDL.Main$.internalOp(Main.scala:726)
        at dxWDL.Main$.dispatchCommand(Main.scala:752)
        at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:806)
        at dxWDL.Main$delayedInit$body.apply(Main.scala:14)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at dxWDL.Main$.main(Main.scala:14)
        at dxWDL.Main.main(Main.scala)
Caused by: java.lang.RuntimeException: Output file nofile is missing
        at dxWDL.base.AppInternalException.<init>(package.scala:7)
        ... 26 more
```

**Comment by orodeh** [comment]
@jtratner This is correct. The file `nofile` does not exist, so the code fails when it tries to upload it. Try putting `something.txt` there instead.

**Comment by jtratner** [comment]
@orodeh - it's an optional file - so it should be detecting that it's not present and not attempting to upload it.  Otherwise how do you have optional outputs?  What's the point of an optional type if not?

I realize I didn't fix up the specification here - https://github.com/openwdl/wdl/pull/310 - but in cromwell (and in dxWDL 0.81.5) you were able to specify an optional file and the system would allow it to not exist and not attempt to upload it.

**Comment by jtratner** [comment]
In cromwell, running this task produces:

```
{"non_existent_file": null}
```

for outputs

**Comment by orodeh** [comment]
Is this in the WDL specification?

**Comment by jtratner** [comment]
It's *almost* in the WDL specification? See here - https://github.com/openwdl/wdl/pull/310/files - and it's definitely how cromwell works and really, really, annoying to write WDL code if it's *not* supported :-/ (because then you can't write generic tasks with optional files inside of them depending on outputs)

Certainly in cromwell this works now.

**Comment by orodeh** [comment]
I see, alright, I'll reopen and implement this.

**Comment by jtratner** [comment]
If you want to do just `File?` and not support `Array[File?]` I'm cool with that for now (since I'm guessing that could be controversial in spec); I will say that we currently use `Array[File?]` in our pipeline tho :P

**Comment by orodeh** [comment]
I believe release [1.17](https://github.com/dnanexus/dxWDL/releases/tag/1.17) fixes this issue, including the case of `Array[File?]`.

**Comment by jtratner** [comment]
thanks @orodeh! I'll test it out! :)

**Comment by orodeh** [comment]
I believe this works now. I will reopen if it still doesn't work.
