### ISSUE TITLE
Task not found when compiling.

### ISSUE THREAD

**Issue by ottojolanki** [dnanexus/dxWDL#303]
I am on macOS high sierra 10.13.6 (17G8030). I am running java 1.8.0_192. The version of dxWDL is 1.21 (dxWDL-1.21.jar). I am trying to compile https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/dev1.1/rna-seq-pipeline.wdl with command:

    (dx-tools) DN52esb4:dxWDL otto$ java -jar dxWDL-1.21.jar  compile ~/github/rna-seq-pipeline/rna-seq-pipeline.wdl -project project-myprojecthash -extras docker_opts.json

the content of `docker_opts.json` is 
```
{
    "default_runtime_attributes" : {
      "docker" : "quay.io/encode-dcc/rna-seq-pipeline:dev1.1_555b6f51-c353-415c-b5de-1dc06174f935"
    }
}
```

I get an error message:
```
java.lang.Exception: Did not find task rna_qc
	at dxWDL.compiler.GenerateIR.compileTask2$1(GenerateIR.scala:140)
	at dxWDL.compiler.GenerateIR.compileCallable(GenerateIR.scala:150)
	at dxWDL.compiler.GenerateIR.$anonfun$apply$5(GenerateIR.scala:228)
	at dxWDL.compiler.GenerateIR.$anonfun$apply$5$adapted(GenerateIR.scala:220)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at dxWDL.compiler.GenerateIR.apply(GenerateIR.scala:220)
	at dxWDL.compiler.Top.womToIR(Top.scala:255)
	at dxWDL.compiler.Top.apply(Top.scala:309)
	at dxWDL.Main$.compile(Main.scala:431)
	at dxWDL.Main$.dispatchCommand(Main.scala:751)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:808)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:14)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at dxWDL.Main$.main(Main.scala:14)
	at dxWDL.Main.main(Main.scala)
```

Could you help me figure out what is wrong here? Thank you!

**Comment by orodeh** [comment]
This sounds like this dxWDL parser limitation that I just documented https://github.com/dnanexus/dxWDL/blob/master/README.md#strict-syntax. Can you check if you have something like this in the WDL code?

**Comment by ottojolanki** [comment]
Thank you for the quick answer @orodeh  This was my first instinct as well, and I did a quick check before making the issue. I'll check thoroughly and report back.

**Comment by ottojolanki** [comment]
The problem was that all the task definitions were indented. Unindenting everything fixed my issue. Closing.
