### ISSUE TITLE
dxWDL should support nested imports

### ISSUE THREAD

**Issue by nh13** [dnanexus/dxWDL#316]
Please see the example WDL files in this archive: [test.zip](https://github.com/dnanexus/dxWDL/files/3709608/test.zip)

Running Cromwell's `womtool` (v47) reports success, similarly for `miniwdl check`.  But with `dxwdl` I get some import errors (see below).  This only occurs if I have two or more levels of imports.  In this example, `main.wdl` imports `util/util.wdl`, which in turn imports `util/other.wdl`.  I think the issue is `dxwdl` is importing relative to the directory from `main.wdl` when importing `other.wdl` from within `util.wdl` (in the `util` sub-folder).  When importing from `util.wdl`, it should be relative to `util.wdl`'s directory (which is `util`).

```
./dxwdl compile main.wdl  -verbose -project <redacted>
v1.32
project ID: <redacted>
folder: /
java.lang.Exception: WOM validation errors:
 NonEmptyList(Failed to import 'util/util.wdl' (reason 1 of 4): Failed to import 'other.wdl' (reason 1 of 4): Failed to resolve 'other.wdl' using resolver: 'relative to directory [...]/test (escaping allowed)' (reason 1 of 1): File not found: other.wdl, Failed to import 'util/util.wdl' (reason 2 of 4): Failed to import 'other.wdl' (reason 2 of 4): Failed to resolve 'other.wdl' using resolver: 'entire local filesystem (relative to '/')' (reason 1 of 1): File not found: other.wdl, Failed to import 'util/util.wdl' (reason 3 of 4): Failed to import 'other.wdl' (reason 3 of 4): Failed to resolve 'other.wdl' using resolver: 'relative to directory [...]/test (escaping allowed)' (reason 1 of 1): File not found: other.wdl, Failed to import 'util/util.wdl' (reason 4 of 4): Failed to import 'other.wdl' (reason 4 of 4): Failed to resolve 'other.wdl' using resolver: 'http importer (no 'relative-to' origin)' (reason 1 of 1): Relative path)

	at dxWDL.util.ParseWomSourceFile.getBundle(ParseWomSourceFile.scala:136)
	at dxWDL.util.ParseWomSourceFile.apply(ParseWomSourceFile.scala:196)
	at dxWDL.compiler.Top.womToIR(Top.scala:218)
	at dxWDL.compiler.Top.apply(Top.scala:290)
	at dxWDL.Main$.compile(Main.scala:446)
	at dxWDL.Main$.dispatchCommand(Main.scala:780)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:837)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:14)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at dxWDL.Main$.main(Main.scala:14)
	at dxWDL.Main.main(Main.scala)
```

**Comment by orodeh** [comment]
If you try *running* Cromwell, you will get the following error:

```
Failed to import 'util/util.wdl' (reason 1 of 3): Failed to resolve 'util/util.wdl' using resolver: 'relative to directory [...]/imports (escaping allowed)' (reason 1 of 1): File not found: util/util.wdl
Failed to import 'util/util.wdl' (reason 2 of 3): Failed to resolve 'util/util.wdl' using resolver: 'entire local filesystem (relative to '/')' (reason 1 of 1): File not found: util/util.wdl
Failed to import 'util/util.wdl' (reason 3 of 3): Failed to resolve 'util/util.wdl' using resolver: 'http importer (no 'relative-to' origin)' (reason 1 of 1): Relative path
```

dxWDL uses the same import logic. The solution is to add `util` to your import list. For example:
```
java -jar dxWDL-v1.32.jar compile test/imports/multi_level/main.wdl -imports test/imports/multi_level/util --project dxWDL_playground
```
