### ISSUE TITLE
`sub()` cannot reference output of `sub(basename(file1))`

### ISSUE THREAD

**Issue by ying-w** [dnanexus/dxWDL#339]
Minimal example:

```wdl
version 1.0
# using dxwdl v1.36.1
workflow test {
    input {
        File f1
    }
    call t1 {
        input:
            file1 = f1
    }
}

task t1 {
    input {
        File file1

        # this should work but doesn't
        String shortname = sub(basename(file1), "_S.*_R1_.*.fastq.gz", "")  # basename() returns string
        # String prefix = sub(shortname, ".*-", "") # this line doesn't work
        String prefix = ""

        # this does work
        String chocolate = 'latte'
        String best_chocolate = sub(chocolate, "latte", "cake")
    }
    command <<<
        echo ~{prefix}
    >>>
}
```

An extension of [example 2](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#string-substring-string-string) where you want to work off of the string that's returned. 

Error given is:

```
java.lang.Exception: WOM validation errors:
 NonEmptyList(Failed to process task definition 't1' (reason 1 of 1): Failed to process expression 'select_first([prefix, sub(shortname, ".*-", "")])' (reason 1 of 1): Invalid parameter 'IdentifierLookup(shortname)'. Expected 'File' but got 'String?')

	at dxWDL.util.ParseWomSourceFile.getBundle(ParseWomSourceFile.scala:136)
	at dxWDL.util.ParseWomSourceFile.apply(ParseWomSourceFile.scala:196)
	at dxWDL.compiler.Top.womToIR(Top.scala:222)
	at dxWDL.compiler.Top.apply(Top.scala:305)
	at dxWDL.Main$.compile(Main.scala:463)
	at dxWDL.Main$.dispatchCommand(Main.scala:808)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:865)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:14)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at dxWDL.Main$.main(Main.scala:14)
	at dxWDL.Main.main(Main.scala)
```

**Comment by orodeh** [comment]
Does this work with Cromwell? It looks like a WOM error.

**Comment by ying-w** [comment]
same error in cromwell, passes miniwdl check though, what should my next steps be?

**Comment by orodeh** [comment]
I am using the Cromwell WOM library, so, you'll need to fix the WDL code. The other way, is to fix the Cromwell code, but that is up to you.  I suggest running the womtool on the WDL code to validate it.

**Comment by ying-w** [comment]
created ticket with broad https://broadworkbench.atlassian.net/browse/BA-6148
i'll work around it
