### ISSUE TITLE
Error compiling with five-dollar-genome workflow

### ISSUE THREAD

**Issue by adily777** [dnanexus/dxWDL#341]
Hello,

I'm trying compile the five-dollar-genome-analysis-pipeline workflow shared by the Broad.
I changed the imports to be local imports with the right paths.
And I get the next error message:

dxWDL workflows ignore their parameter meta section
java.lang.Exception: Did not find sources for workflow WholeGenomeGermlineSingleSample
        at dxWDL.compiler.GenerateIR.compileCallable(GenerateIR.scala:156)
        at dxWDL.compiler.GenerateIR.$anonfun$apply$5(GenerateIR.scala:230)
        at dxWDL.compiler.GenerateIR.$anonfun$apply$5$adapted(GenerateIR.scala:222)
        .....

What can be the reason for that?

Thanks for your help.

**Comment by orodeh** [comment]
This looks like an error in the paths of the imported files. Note that you can use http imports, there should be no need to modify the import paths. One way to make progress is to compile with the `--verbose` flag, it should give you more information on what is going on.

**Comment by adily777** [comment]
Thanks for your response.
I used local imports because I did some changes at the run time parameters of the tasks (I don't use google cloud platform).
I compiled with the `--verbose` flag, and it seems that it recognized correctly the imports paths, but still the same error:

```
found 12 new WDL source files
dxWDL workflows ignore their parameter meta section
IR pass
  tasks=Set(MarkDuplicates, CollectAggregationMetrics, CollectQualityYieldMetrics, GetBwaVersion, BaseRecalibrator, HaplotypeCaller_GATK35_GVCF, CNNScoreVariants, ConvertToCram, FastqToUnmappedBamTask, ApplyBQSR, HardFilterVcf, CollectReadgroupBamQualityMetrics, GatherUnsortedBamFiles, SamToFastqAndBwaMemAndMba, MergeVCFs, SamSplitter, SortSamSpark, CheckFingerprint, CreateSequenceGroupingTSV, CalculateReadGroupChecksum, HaplotypeCaller_GATK4_VCF, CheckContamination, CrossCheckFingerprints, ScatterIntervalList, GatherBqsrReports, FilterVariantTranches, ValidateVCF, MergeBamouts, CollectUnsortedReadgroupBamQualityMetrics, SumFloats, CollectWgsMetrics, ConvertToBam, CheckPreValidation, GatherSortedBamFiles, CollectHsMetrics, CollectVariantCallingMetrics, ValidateSamFile, SortSam, MarkDuplicatesSpark, CollectRawWgsMetrics)
  sortByDependencies List(MarkDuplicates, CollectAggregationMetrics, CollectQualityYieldMetrics, GetBwaVersion, BaseRecalibrator, HaplotypeCaller_GATK35_GVCF, CNNScoreVariants, FastqToUnmappedBam, ConvertToCram, FastqToUnmappedBamTask, ApplyBQSR, HardFilterVcf, SplitLargeReadGroup, CollectReadgroupBamQualityMetrics, GatherUnsortedBamFiles, SamToFastqAndBwaMemAndMba, UnmappedBamToAlignedBam, MergeVCFs, SamSplitter, SortSamSpark, CheckFingerprint, WholeGenomeGermlineSingleSample, CreateSequenceGroupingTSV, CalculateReadGroupChecksum, HaplotypeCaller_GATK4_VCF, AggregatedBamQC, CheckContamination, CrossCheckFingerprints, ScatterIntervalList, GatherBqsrReports, FilterVariantTranches, ValidateVCF, MergeBamouts, CollectUnsortedReadgroupBamQualityMetrics, BamToCram, SumFloats, CollectWgsMetrics, ConvertToBam, CheckPreValidation, GatherSortedBamFiles, CollectHsMetrics, VariantCalling, CollectVariantCallingMetrics, ValidateSamFile, SortSam, MarkDuplicatesSpark, CollectRawWgsMetrics)
    depOrder =Vector(MarkDuplicates, CollectAggregationMetrics, CollectQualityYieldMetrics, GetBwaVersion, BaseRecalibrator, HaplotypeCaller_GATK35_GVCF, CNNScoreVariants, ConvertToCram, ApplyBQSR, HardFilterVcf, CollectReadgroupBamQualityMetrics, GatherUnsortedBamFiles, SamToFastqAndBwaMemAndMba, MergeVCFs, SamSplitter, SortSamSpark, CheckFingerprint, CreateSequenceGroupingTSV, CalculateReadGroupChecksum, HaplotypeCaller_GATK4_VCF, CheckContamination, CrossCheckFingerprints, ScatterIntervalList, GatherBqsrReports, FilterVariantTranches, ValidateVCF, MergeBamouts, CollectUnsortedReadgroupBamQualityMetrics, SumFloats, CollectWgsMetrics, ConvertToBam, CheckPreValidation, GatherSortedBamFiles, CollectHsMetrics, CollectVariantCallingMetrics, ValidateSamFile, SortSam, MarkDuplicatesSpark, CollectRawWgsMetrics, FastqToUnmappedBam, SplitLargeReadGroup, AggregatedBamQC, BamToCram, VariantCalling, UnmappedBamToAlignedBam, WholeGenomeGermlineSingleSample)
  Compiling task MarkDuplicates
  Compiling task CollectAggregationMetrics
  Compiling task CollectQualityYieldMetrics
  Compiling task GetBwaVersion
  Compiling task BaseRecalibrator
  Compiling task HaplotypeCaller_GATK35_GVCF
  Compiling task CNNScoreVariants
  Compiling task ConvertToCram
  Compiling task ApplyBQSR
  Compiling task HardFilterVcf
  Compiling task CollectReadgroupBamQualityMetrics
  Compiling task GatherUnsortedBamFiles
  Compiling task SamToFastqAndBwaMemAndMba
  Compiling task MergeVCFs
  Compiling task SamSplitter
  Compiling task SortSamSpark
  Compiling task CheckFingerprint
  Compiling task CreateSequenceGroupingTSV
  Compiling task CalculateReadGroupChecksum
  Compiling task HaplotypeCaller_GATK4_VCF
  Compiling task CheckContamination
  Compiling task CrossCheckFingerprints
  Compiling task ScatterIntervalList
  Compiling task GatherBqsrReports
  Compiling task FilterVariantTranches
  Compiling task ValidateVCF
  Compiling task MergeBamouts
  Compiling task CollectUnsortedReadgroupBamQualityMetrics
  Compiling task SumFloats
  Compiling task CollectWgsMetrics
  Compiling task ConvertToBam
  Compiling task CheckPreValidation
  Compiling task GatherSortedBamFiles
  Compiling task CollectHsMetrics
  Compiling task CollectVariantCallingMetrics
  Compiling task ValidateSamFile
  Compiling task SortSam
  Compiling task MarkDuplicatesSpark
  Compiling task CollectRawWgsMetrics
  compiling workflow SplitLargeReadGroup
Assembling workflow backbone SplitLargeReadGroup
    inputs= Vector(bwa_commandline, reference_fasta, compression_level, output_bam_basename, input_bam, bwa_version, reads_per_file, papi_settings)
    Compiling fragment <frag SamSplitter> as stage
    Compiling fragment <scatter (unmapped_bam in SamSplitter.split_bams)> as stage
    compileNestedBlock, closureInputs=
 Map(SamToFastqAndBwaMemAndMba.output_bam -> WomSingleFileType)
    Assembling workflow backbone SplitLargeReadGroup_block_1
      inputs= Vector(papi_settings, bwa_commandline, bwa_version, compression_level, unmapped_bam, reference_fasta, SamToFastqAndBwaMemAndMba.output_bam)
      Compiling fragment <frag SamToFastqAndBwaMemAndMba> as stage
      Compiling fragment <eval> as stage
    Compiling fragment <frag SumSplitAlignedSizes> as stage
    Compiling fragment <frag GatherMonolithicBamFile> as stage
  compiling workflow AggregatedBamQC
  Assembling workflow backbone AggregatedBamQC
    inputs= Vector(haplotype_database_file, base_recalibrated_bam_index, recalibrated_bam_base_name, references, base_name, base_recalibrated_bam, sample_name, papi_settings)
    Compiling fragment <frag CollectReadgroupBamQualityMetrics> as stage
    Compiling fragment <frag CollectAggregationMetrics> as stage
    Compiling fragment <if ((defined(haplotype_database_file) && defined(references.fingerprint_genotypes_file)))> as stage
```
.... (and so for each workflow - compiling workflow X
                                                 Assembling workflow backbone X
                                                 ...)
```
Assembling workflow backbone UnmappedBamToAlignedBam_block_1
      inputs= Vector(unmapped_bam, references, bwa_commandline, cutoff_for_large_rg_in_gb, compression_level, unmapped_bam_suffix, papi_settings, SamToFastqAndBwaMemAndMba.output_bam, unmapped_bam_basename, GetBwaVersion.bwa_version, unmapped_bam_size, output_aligned_bam, SplitRG.aligned_bam)
      Compiling fragment <frag CollectQualityYieldMetrics> as stage
      Compiling fragment <if ((unmapped_bam_size > cutoff_for_large_rg_in_gb))> as stage
      Compiling fragment <if ((unmapped_bam_size <= cutoff_for_large_rg_in_gb))> as stage
      Compiling fragment <frag CollectUnsortedReadgroupBamQualityMetrics> as stage
      Compiling fragment <eval> as stage
    Compiling fragment <frag SumFloats> as stage
    Compiling fragment <frag MarkDuplicates> as stage
    Compiling fragment <frag SortSampleBam> as stage
    Compiling fragment <if (defined(haplotype_database_file))> as stage
    Compiling fragment <frag CreateSequenceGroupingTSV> as stage
    Compiling fragment <frag CheckContamination> as stage
    Compiling fragment <scatter (subgroup in CreateSequenceGroupingTSV.sequence_grouping)> as stage
    Compiling fragment <frag GatherBqsrReports> as stage
    Compiling fragment <scatter (subgroup in CreateSequenceGroupingTSV.sequence_grouping_with_unmapped)> as stage
    Compiling fragment <frag GatherBamFiles> as stage
java.lang.Exception: Did not find sources for workflow WholeGenomeGermlineSingleSample
        at dxWDL.compiler.GenerateIR.compileCallable(GenerateIR.scala:154)
        at dxWDL.compiler.GenerateIR.$anonfun$apply$5(GenerateIR.scala:228)
        at dxWDL.compiler.GenerateIR.$anonfun$apply$5$adapted(GenerateIR.scala:220)
        ...
```
When I looked into the code I found that this error is received by the next code:
dxWDL/src/main/scala/dxWDL/compiler/GenerateIR.scala:
```
            case wf: WorkflowDefinition =>
                workflowDir.get(wf.name) match {
                    case None =>
                        throw new Exception(s"Did not find sources for workflow ${wf.name}")
                    case Some(wfSource) =>
                        compileWorkflow(wf, typeAliases, wfSource, callables, language, locked, reorg)
        ...
        val workflowDir = allSources.foldLeft(Map.empty[String, String]) {
            case (accu, (filename, srcCode)) =>
                ParseWomSourceFile(verbose.on).scanForWorkflow(srcCode) match {
                    case None =>
                        accu
                    case Some((wfName, wfSource)) =>
                        accu + (wfName -> wfSource)
                }
        }
```
dxWDL/src/main/scala/dxWDL/util/ParseWomSourceFile.scala:
```
    // Go through one WDL source file, and return a map from task name
    // to its source code. Return an empty map if there are no tasks
    // in this file.
    def scanForWorkflow(sourceCode: String) : Option[(String, String)] = {
        val lines = sourceCode.split("\n").toList
        findNextWorkflow(lines) match {
            case None =>
                None
            case Some((remainingLines, wfName, wfLines)) =>
                Some((wfName, wfLines))
        }
    } 
```
Can the problem be becausethere is no task at the main wdl? and the scanForWorkflow return None?

I would appreciate your help.

**Comment by orodeh** [comment]
Did you figure it out?

**Comment by adily777** [comment]
Not yet. I have no idea what the problem can be.

I run the next command:
`java -jar .\dxWDL-v1.36.1.jar compile WholeGenomeGermlineSingleSample.wdl -project project-FFqyQXj0PX9v55F09px1bQJY -destination /genomes_pipeline/five_dollar -defaults WholeGenomeGermlineSingleSample.hg38.inputs.json -imports .\tasks\ --verbose`

I run it from a folder that contains:
WholeGenomeGermlineSingleSample.wdl
WholeGenomeGermlineSingleSample.hg38.inputs.json
dxWDL-v1.36.1.jar
\tasks (a folder that contains all sub-workflow)

The import statements at all wdl files, include the main one, are as:
 `import "BamToCram.wdl" as ToCram`
because I let the flag -imports the folder tasks.

If I change the paths of the imports at the main wdl (WholeGenomeGermlineSingleSample.wdl) to be relative paths like:
 `import "tasks/BamToCram.wdl" as ToCram`
I also get the same error.

What else I can do?

**Comment by orodeh** [comment]
Can you package your WDL files and attach the package? I will take a look at it. 

     Ohad.

**Comment by adily777** [comment]
Thanks a lot!
[five-dollar-genome-analysis-pipeline.zip](https://github.com/dnanexus/dxWDL/files/3978458/five-dollar-genome-analysis-pipeline.zip)

**Comment by orodeh** [comment]
I compiled it like this: 
```
java -jar ~/devel/dxWDL/dxWDL-v1.37.1.jar compile ~/five-dollar-genome-analysis-pipeline/WholeGenomeGermlineSingleSample.wdl --project dxWDL_playground --folder /fiveDollarGenome --input WholeGenomeGermlineSingleSample.hg38.inputs.json
```

into a `dxWDL_playground` which is testing project. The one thing I had to change was un-tabify one of the WDL files, because the WOM parser was complaining.

**Comment by adily777** [comment]
Thank you for your help!

I un-tabify all WDL files, but still getting the same error: 
`java.lang.Exception: Did not find sources for workflow WholeGenomeGermlineSingleSample`

May there is something else that doesn't related to the code itself. 
I run the command from DNAnexus CLI on Windows. Where from you run the command?

And regarding to `dxWDL_playground`, can I access this project?

**Comment by adily777** [comment]
I would really appreciate your help, this issue is urgent from me.

Thanks a lot.

**Comment by adily777** [comment]
Open #341
