### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by adily777** [dnanexus/dxWDL#348]
Hello,

I'm trying compile the five-dollar-genome-analysis-pipeline workflow shared by the Broad.
(this is a continuation of other issue that was closed https://github.com/dnanexus/dxWDL/issues/341)

I get the next error:
`java.lang.Exception: Did not find sources for workflow WholeGenomeGermlineSingleSample`

**Ohad Rodeh** succeseded to compile it but I still get the same error.

The files attached here:
https://github.com/dnanexus/dxWDL/files/3978465/five-dollar-genome-analysis-pipeline.zip

This issue is critical for my work, I would really appreciate your help.

Adily

**Comment by orodeh** [comment]
My best guess is that the problem is that you are using windows, this isn't really supported for dxWDL. Please try it on mac or Linux.

**Comment by adily777** [comment]
Thank you Ohad!

I tried it on linux an got the next error:
```
java -jar dxWDL-v1.37.1.jar compile WholeGenomeGermlineSingleSample.wdl -project project-FFqyQXj0PX9v55F09px1bQJY -folder /genomes_pipeline/five_dollar -inputs WholeGenomeGermlineSingleSample.hg38.inputs.json
```

```
Warning: no DNAnexus security context found.
dxWDL workflows ignore their parameter meta section
Warning: no DNAnexus security context found.
Warning: no DNAnexus security context found.
Warning: no DNAnexus security context found.
Warning: no DNAnexus security context found.
Warning: no DNAnexus security context found.
Warning: no DNAnexus security context found.
Warning: no DNAnexus security context found.
Warning: no DNAnexus security context found.
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:208)
	at dxWDL.dx.DxPath$.parse(DxPath.scala:30)
	at dxWDL.dx.DxPath$.$anonfun$triage$1(DxPath.scala:178)
	at dxWDL.dx.DxPath$.$anonfun$triage$1$adapted(DxPath.scala:177)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at dxWDL.dx.DxPath$.triage(DxPath.scala:177)
```
What can be the reason?

Thanks again,
Adily

**Comment by orodeh** [comment]
I think you aren't logged in. Can you do `dx env` ?

**Comment by adily777** [comment]
I logged in. `dx env` give me:

```
Auth token used		ULot0O6ejaAGr0yBwg6tJANXYdNcMNRH
API server protocol	https
API server host		api.dnanexus.com
API server port		443
Current workspace	project-FZK3v0809bzkY0Bz13Xp2j0F
Current workspace name	"outside_revisions_data_only"
Current folder		/
Current user		elpeleg
```

I should mention that I compile through proxy:
```
sudo https_proxy='https://192.168.12.4:8080' java -jar dxWDL-v1.37.1.jar compile WholeGenomeGermlineSingleSample.wdl -project project-FFqyQXj0PX9v55F09px1bQJY -folder /genomes_pipeline/five_dollar -inputs WholeGenomeGermlineSingleSample.hg38.inputs.json```

**Comment by adily777** [comment]
Thank you for your answer.

When I try `sudo -E`, or running this command without `sudo`, I get this:

```
java.lang.ExceptionInInitializerError
	at dxWDL.dx.DxPath$.resolveProject(DxPath.scala:71)
	at dxWDL.Main$.pathOptions(Main.scala:280)
	at dxWDL.Main$.compile(Main.scala:454)
	at dxWDL.Main$.dispatchCommand(Main.scala:808)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:865)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:14)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at dxWDL.Main$.main(Main.scala:14)
	at dxWDL.Main.main(Main.scala)
Caused by: java.lang.IllegalArgumentException: Invalid HTTP host: 192.168.12.4:8080/
	at org.apache.http.HttpHost.create(HttpHost.java:122)
	at com.dnanexus.DXEnvironment.parseProxyDefinition(DXEnvironment.java:614)
	at com.dnanexus.DXEnvironment.<init>(DXEnvironment.java:506)
	at com.dnanexus.DXEnvironment.<init>(DXEnvironment.java:35)
	at com.dnanexus.DXEnvironment$Builder.build(DXEnvironment.java:267)
	at com.dnanexus.DXEnvironment.create(DXEnvironment.java:473)
	at com.dnanexus.DXObject.<clinit>(DXObject.java:40)
	... 15 more
```
What is the right way to compile through proxy?

Adily

**Comment by adily777** [comment]
When I do as explained here:
https://github.com/dnanexus/dxWDL/blob/master/doc/ExpertOptions.md#proxy-configurations
I get the same ExceptionInInitializerError.

**Comment by orodeh** [comment]
This looks legitimate to me. You may want to investigate what `org.apache.http.HttpHost.create` considers a valid http address.

**Comment by adily777** [comment]
The http address is valid:
```
Python
>>> import validators
>>> validators.url("https://192.168.12.4:8080")
True
```

**Comment by orodeh** [comment]
I filed it as a bug. Try using dxWDL without a proxy, see if that works.

**Comment by ying-w** [comment]
@adily777  you might want to invalidate the token

> ```
> Auth token used		ULot0O6ejaAGr0yBwg6tJANXYdNcMNRH
> ```

**Comment by adily777** [comment]
Hello,
I tried to compile it without proxy, and still get the same assertion error:
```
dxWDL workflows ignore their parameter meta section
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:208)
	at dxWDL.dx.DxPath$.parse(DxPath.scala:30)
	at dxWDL.dx.DxPath$.$anonfun$triage$1(DxPath.scala:178)
	at dxWDL.dx.DxPath$.$anonfun$triage$1$adapted(DxPath.scala:177)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at dxWDL.dx.DxPath$.triage(DxPath.scala:177)
        ...
```
but without the `Warning: no DNAnexus security context found.`

When I compile the five-dollar-genome-analysis-pipeline without my changes, just after cloning it from github, I get the same error!

What can be the reason for that?

Thank you,
Adily

**Comment by sclan** [comment]
Hello Adily,

The assertion error seems to be related to the path in your working project (project-FZK3v0809bzkY0Bz13Xp2j0F). We have inconsistent but similar reports from other users compiling WDL files into a project that has cached files from previous dxWDL compile. Can you try compiling it in a new (empty) project and see if the error goes away?

The "dxWDL workflows ignore their parameter meta section" line is likely a warning. If you a parameter meta block in your WDL code, it is likely to be ignored.

**Comment by adily777** [comment]
Hello,

After many attempts, the problem was at the json file.
The problematic rows were:
```
  "WholeGenomeGermlineSingleSample.references": {
    "fingerprint_genotypes_file": "gs://dsde-data-na12878-public/NA12878.hg38.reference.fingerprint.vcf",
    "fingerprint_genotypes_index": "gs://dsde-data-na12878-public/NA12878.hg38.reference.fingerprint.vcf.idx",
```
When I removed them it compiled!

Thanks a lot for your help,
Adily
