### ISSUE TITLE
Can't use dxni with apps

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#364]
I think it just needs to check if valid dxid?

```
›› dxwdl dxni --path $(cat app_id.json| jq .id) -o out.wdl --project myproject
java.lang.Exception: Path dx:///"app-123" not found req={"name":"\"app-123\"","folder":"/"}, i=0, project=project-123
	at dxWDL.dx.DxPath$.$anonfun$submitRequest$2(DxPath.scala:139)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at dxWDL.dx.DxPath$.submitRequest(DxPath.scala:133)
	at dxWDL.dx.DxPath$.$anonfun$resolveBulk$1(DxPath.scala:212)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at dxWDL.dx.DxPath$.resolveBulk(DxPath.scala:210)
	at dxWDL.dx.DxPath$.resolveOnePath(DxPath.scala:220)
	at dxWDL.compiler.DxNI.dxWDL$compiler$DxNI$$fullPath(DxNI.scala:181)
	at dxWDL.compiler.DxNI$.apply(DxNI.scala:384)
	at dxWDL.Main$.dxniApplets(Main.scala:547)
	at dxWDL.Main$.dxni(Main.scala:579)
	at dxWDL.Main$.dispatchCommand(Main.scala:894)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:951)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:12)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at dxWDL.Main$.main(Main.scala:12)
	at dxWDL.Main.main(Main.scala)
```

**Comment by orodeh** [comment]
The intention was for the path argument to be a platform folder. I can extend it to take an app-id as well.

**Comment by jtratner** [comment]
That’d be awesome - thanks! :)

**Comment by jtratner** [comment]
(I think fair to just support app ID and not app name if ya want)

**Comment by orodeh** [comment]
It is part of release [v1.45](https://github.com/dnanexus/dxWDL/releases/tag/v1.45). The path argument can now take app-ids and applet-ids.
