### ISSUE TITLE
Error folder upload

### ISSUE THREAD

**Issue by FabianDK** [dnanexus/dxWDL#481]
Hello, 

I have written my wdl workflow and compiled it with dxWDL. My output is a folder, however, I am getting an error when I run the applet due to "dx upload" leaving out the -r option per default (see below).

Is there a way to compile the applet specifying that the output will be a folder that should be uploaded on the platform?

Thanks!

Last part of log file:
```
+ java -jar /dxWDL.jar internal taskEpilog /home/dnanexus 1 PerFile
Epilog  debugLevel=1
upload file my_output_folder (try=0)
--  dx upload "my_output_folder" --brief
STDOUT: 
STDERR: Error: my_output_folder is a directory but the -r/--recursive option was not given
java.lang.Exception: Failure to upload file my_output_folder
	at dxWDL.dx.DxUtils$.uploadFile(DxUtils.scala:360)
	at dxWDL.exec.JobInputOutput.$anonfun$delocalizeFiles$5(JobInputOutput.scala:439)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at dxWDL.exec.JobInputOutput.delocalizeFiles(JobInputOutput.scala:437)
	at dxWDL.exec.TaskRunner.epilog(TaskRunner.scala:543)
	at dxWDL.Main$.taskAction(Main.scala:757)
	at dxWDL.Main$.internalOp(Main.scala:1030)
	at dxWDL.Main$.dispatchCommand(Main.scala:1058)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:1123)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at dxWDL.Main$.main(Main.scala:13)
	at dxWDL.Main.main(Main.scala)
[31mfailure running TaskEpilog[0m
```

**Comment by jdidion** [comment]
dxWDL does not support the input or output of directories. The WDL development version adds support for the `Directory` data type, and the new [dxCompiler](https://github.com/dnanexus/dxCompiler) tool will eventually support this. The current recommendation is to tar the output directory and output it as a single file.
